version: '3'

services:
  node:
    build:
      context: .
      dockerfile: dockerfile.node
    image: rafaelcecchin/node
    container_name: node
    networks:
      - nodenet
    ports:
      - "3000:3000"

  nginx:
    build:
      context: .
      dockerfile: dockerfile.nginx
    image: rafaelcecchin/nginx
    container_name: nginx
    networks:
      - nodenet
    ports:
      - "80:80"
    
  db:
    build:
      context: .
      dockerfile: dockerfile.mysql
    image: rafaelcecchin/mysql
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./db:/var/lib/mysql
      - ./migrations:/root/migrations
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenet

networks:
  nodenet:
    driver: bridge
