version: '3'

services:
  node:
    build:
      context: .
      dockerfile: dockerfile.node
    image: rafaelcecchin/node
    container_name: node
    tty: true
    volumes:
      - ./app:/usr/src/app
    networks:
      - nodenet
    ports:
      - "3000:3000"
    command: >
      sh -c "npm install && node index.js"

  nginx:
    build:
      context: .
      dockerfile: dockerfile.nginx
    image: rafaelcecchin/nginx
    container_name: nginx
    networks:
      - nodenet
    ports:
      - "80:80"
    
  db:
    image: mysql:5.7.16
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./db:/var/lib/mysql
      - ./migrations:/root/migrations
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenet
    entrypoint: /bin/bash -c "/root/migrations/migrate.sh & /entrypoint.sh mysqld"

networks:
  nodenet:
    driver: bridge
