USE nodedb;

INSERT INTO people (name) VALUES 
    ("Zezé Di Camargo"),
    ("Luciano"),
    ("Chitãozinho"),
    ("Xororó"),
    ("Jorge"),
    ("Mateus"),
    ("Fernando"),
    ("Sorocaba"),
    ("Victor"),
    ("Leo"),
    ("Bruno"),
    ("Marrone"),
    ("César Menotti"),
    ("Fabiano"),
    ("Zé Neto"),
    ("Cristiano"),
    ("Henrique"),
    ("Juliano"),
    ("Gusttavo"),
    ("Lima"),
    ("Luan"),
    ("Santana"),
    ("Marília"),
    ("Mendonça"),
    ("Maiara"),
    ("Maraísa"),
    ("Simone"),
    ("Simaria"),
    ("Matheus"),
    ("Kauan"),
    ("João Bosco"),
    ("Vinícius"),
    ("Munhoz"),
    ("Mariano"),
    ("João Neto"),
    ("Frederico"),
    ("Cleber"),
    ("Cauan"),
    ("Rick"),
    ("Renner");