INSERT INTO people (name) VALUES 
    ("Zezé Di Camargo"),
    ("Luciano"),
    ("Chitãozinho"),
    ("Xororó"),
    ("Jorge"),
    ("Mateus"),
    ("Fernando"),
    ("Sorocaba"),
    ("Victor"),
    ("Leo"),
    ("Bruno"),
    ("Marrone"),
    ("César Menotti"),
    ("Fabiano"),
    ("Zé Neto"),
    ("Cristiano"),
    ("Henrique"),
    ("Juliano"),
    ("Gusttavo"),
    ("Lima"),
    ("Luan"),
    ("Santana"),
    ("Marília"),
    ("Mendonça"),
    ("Maiara"),
    ("Maraísa"),
    ("Simone"),
    ("Simaria"),
    ("Matheus"),
    ("Kauan");